<?xml version="1.0" encoding="utf-8"?><Database Name="Database" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\Database.mdf;Integrated Security=True" SettingsObjectName="WOZAP.Properties.Settings" SettingsPropertyName="DatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.id_message" Member="id_messages">
    <Type Name="id_message">
      <Column Name="id_first" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_second" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="message" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.id_name" Member="id_names">
    <Type Name="id_name">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>